# Generated by Django 6.0.5 on 2026-05-31 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_changed_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Последнее изменение пароля",
            ),
            preserve_default=False,
        ),
    ]
