# Generated by Django 6.0.5 on 2026-05-18 11:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_full_name_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Обязательное поле для клиента', max_length=128, null=True, region='RU', unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Для клиента может быть сгенерировано автоматически на основе его номера телефона', max_length=150, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
