# Generated by Django 6.0.5 on 2026-06-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0006_alter_category_options_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "dish",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.dish",
                        verbose_name="Блюдо",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция баннера",
                "verbose_name_plural": "позиции баннера",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DishCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "dishes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dishes",
                        to="menu.dish",
                        verbose_name="Блюда",
                    ),
                ),
            ],
            options={
                "verbose_name": "подборка блюд",
                "verbose_name_plural": "подборки блюд",
                "ordering": ["order", "title"],
            },
        ),
    ]
