# Generated by Django 6.0.5 on 2026-05-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("menu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="cartdish",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="cart.cart",
                verbose_name="Корзина",
            ),
        ),
        migrations.AddField(
            model_name="cartdish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_positions",
                to="menu.dish",
                verbose_name="Блюдо",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartdish",
            constraint=models.UniqueConstraint(
                fields=("cart", "dish"), name="unique_dish_in_cart"
            ),
        ),
    ]
