# Generated by Django 6.0.5 on 2026-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
        ("menu", "0005_alter_dish_max_per_order_dish_max_per_order_gte_1"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartdish",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="quantity_gte_1"
            ),
        ),
    ]
