# Generated by Django 6.0.5 on 2026-06-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartdish_quantity_gte_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdish",
            name="is_selected",
            field=models.BooleanField(default=True, verbose_name="Выбрано для заказа"),
        ),
    ]
