# Generated by Django 6.0.5 on 2026-06-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cartdish_is_selected"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartdish",
            options={
                "ordering": ["-pk"],
                "verbose_name": "позиция в корзине",
                "verbose_name_plural": "позиции в корзинах",
            },
        ),
    ]
