# Generated by Django 6.0.5 on 2026-05-17 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL-идентификатор категории (используется в маршрутах вместо ID)', unique=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Значение для фильтрации через query параметр (?tag=...)', unique=True)),
            ],
            options={
                'verbose_name': 'тэг блюда',
                'verbose_name_plural': 'тэги блюд',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL-идентификатор подкатегории (используется в маршрутах вместо ID)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.category', verbose_name='Основная категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (₽)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес (г)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для приобретения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('max_quantity_per_order', models.PositiveIntegerField(default=10, help_text='Максимальное количество в одном заказе', verbose_name='Макс. в заказе')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.subcategory', verbose_name='Подкатегория')),
                ('tags', models.ManyToManyField(blank=True, related_name='dishes', to='menu.tag', verbose_name='Тэги блюда')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='Изображение')),
                ('image_type', models.CharField(choices=[('main', 'Главное'), ('card', 'Для карточки в каталоге')], default='main', max_length=20, verbose_name='Тип изображения')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'изображение блюда',
                'verbose_name_plural': 'изображения блюд',
                'constraints': [models.UniqueConstraint(fields=('dish', 'image_type'), name='unique_image_type_per_dish')],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_subcategory_slug_per_category'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['is_available'], name='menu_dish_is_avai_5ebb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['subcategory', 'is_available'], name='menu_dish_subcate_7107f0_idx'),
        ),
    ]
