# Generated by Django 6.0.5 on 2026-05-30 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="calories_100",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ккал (в\xa0100\xa0г)"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="carbs_100",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Углеводы (в\xa0100\xa0г)"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="fats_100",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Жиры (в\xa0100\xa0г)"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="proteins_100",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Белки (в\xa0100\xa0г)"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dishes",
                to="menu.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
