# Generated by Django 6.0.5 on 2026-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Отображается в меню и доступно для приобретения', verbose_name='Доступно'),
        ),
    ]
