# Generated by Django 6.0.5 on 2026-06-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_dish_calories_100_alter_dish_carbs_100_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dishes",
                to="menu.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
