# Generated by Django 6.0.5 on 2026-05-18 23:04

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(upload_to=menu.models.upload_image_path, verbose_name='Изображение'),
        ),
    ]
