# Generated by Django 6.0.5 on 2026-06-01 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_dish_subcategory"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dish",
            name="menu_dish_is_avai_5ebb9b_idx",
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="max_quantity_per_order",
            new_name="max_per_order",
        ),
        migrations.AlterField(
            model_name="dish",
            name="discount_percent",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка (%)",
            ),
        ),
        migrations.AddConstraint(
            model_name="dish",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_percent__lte", 100)),
                name="discount_percent_lte_100",
            ),
        ),
    ]
