# Generated by Django 6.0.5 on 2026-06-02 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_remove_dish_menu_dish_is_avai_5ebb9b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="max_per_order",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Максимальное количество в одном заказе",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Макс. в заказе",
            ),
        ),
        migrations.AddConstraint(
            model_name="dish",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_per_order__gte", 1)),
                name="max_per_order_gte_1",
            ),
        ),
    ]
