# Generated by Django 6.0.5 on 2026-06-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_dish_max_per_order_dish_max_per_order_gte_1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["title"],
                "verbose_name": "подкатегория",
                "verbose_name_plural": "подкатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["title"],
                "verbose_name": "тэг блюда",
                "verbose_name_plural": "тэги блюд",
            },
        ),
    ]
