# Generated by Django 6.0.5 on 2026-06-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_category_options_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order"],
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["order"],
                "verbose_name": "подкатегория",
                "verbose_name_plural": "подкатегории",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок отображения на сайте",
                verbose_name="Порядок",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок отображения на сайте",
                verbose_name="Порядок",
            ),
        ),
    ]
