# Generated by Django 6.0.5 on 2026-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_alter_category_options_alter_subcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["order"],
                "verbose_name": "тэг блюда",
                "verbose_name_plural": "тэги блюд",
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок отображения на сайте",
                verbose_name="Порядок",
            ),
        ),
    ]
