# Generated by Django 6.0.5 on 2026-05-30 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("cooking", "Готовится"),
                            ("delivery", "Доставляется"),
                            ("done", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("address", models.TextField(verbose_name="Адрес доставки")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Пересчитывается автоматически при сохранении",
                        max_digits=10,
                        verbose_name="Итоговая цена (₽)",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "dish_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Сохраняется автоматически из блюда при создании позиции и не меняется при изменеии исходного блюда",
                        max_digits=10,
                        verbose_name="Цена блюда (₽)",
                    ),
                ),
                (
                    "dish_title",
                    models.CharField(
                        blank=True,
                        help_text="Сохраняется автоматически из блюда при создании позиции и не меняется при изменении исходного блюда",
                        max_length=200,
                        verbose_name="Название блюда",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция в заказе",
                "verbose_name_plural": "позиции в заказах",
            },
        ),
    ]
