# Generated by Django 6.0.5 on 2026-05-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Заказ может быть оформлен только клиентом",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="orderdish",
            name="dish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_positions",
                to="menu.dish",
                verbose_name="Блюдо",
            ),
        ),
        migrations.AddField(
            model_name="orderdish",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dishes",
            field=models.ManyToManyField(
                related_name="orders",
                through="orders.OrderDish",
                to="menu.dish",
                verbose_name="Блюда",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderdish",
            constraint=models.UniqueConstraint(
                fields=("order", "dish"), name="unique_dish_in_order"
            ),
        ),
    ]
