# Generated by Django 6.0.5 on 2026-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderdish',
            options={'verbose_name': 'позиция в заказе', 'verbose_name_plural': 'позиции в заказах'},
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
