# Generated by Django 6.0.5 on 2026-05-18 19:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_is_available'),
        ('orders', '0003_alter_order_options_alter_orderdish_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderDish', to='menu.dish', verbose_name='Блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('delivery', 'Доставляется'), ('done', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Пересчитывается автоматически при сохранении', max_digits=10, verbose_name='Итоговая цена (₽)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Заказ может быть оформлен только клиентом', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_positions', to='menu.dish', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сохраняется автоматически из блюда при создании позиции и не меняется при изменеии исходного блюда', max_digits=10, verbose_name='Цена блюда (₽)'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish_title',
            field=models.CharField(blank=True, help_text='Сохраняется автоматически из блюда при создании позиции и не меняется при изменении исходного блюда', max_length=200, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
    ]
