# Generated by Django 6.0.5 on 2026-06-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_total_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdish",
            options={
                "ordering": ["dish_title"],
                "verbose_name": "позиция в заказе",
                "verbose_name_plural": "позиции в заказах",
            },
        ),
    ]
